# Official web site https://docs.astral.sh/ruff/rules/
# github actions https://github.com/astral-sh/ruff/blob/main/docs/configuration.md
target-version = "py312"

exclude = ["**/tests/"]
line-length = 100

[lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "B",  # flake8-bugbear
    "N",  # pep8-naming
    "W",  # pycodestyle
    "UP", # pyupgrade
]
